### ISSUE TITLE
issue with DatePicker control

### ISSUE THREAD

**Issue by utilitka3** [LDWils/Tafe18S108#4]
Hi mates,
I need some help to resolve my problem with datePicker control. Can you have a look my code and give me some advise how can I solve it.

Thanks.

**Comment by LDWils** [comment]
Hi Alexandra,

You can see my code regarding the datepicker as I have also used one. This code was actually taken from elsewhere in the StartFinance project as well.

```
                            string CDay = _ShoppingDate.Date.Day.ToString();
                            string CMonth = _ShoppingDate.Date.Month.ToString();
                            string CYear = _ShoppingDate.Date.Year.ToString();
                            string FinalDate = "" + CMonth + "/" + CDay + "/" + CYear;
```
